### ISSUE TITLE
Encode and decode, different checksum

### ISSUE THREAD

**Issue by roccomuso** [node-ebml/node-ebml#33]
```javascript
const ebml = require('ebml')
const fs = require('fs')

let ebmlDecoder = new ebml.Decoder()
let ebmlEncoder = new ebml.Encoder()

let i = fs.createReadStream('./input.mkv')
let o = fs.createWriteStream('./output.mkv')

i.pipe(ebmlDecoder).pipe(ebmlEncoder).pipe(o)
```

`input.mkv` and `output.mkv` have a different checksum.

I read that some elements are `discardable`. Are those discarded by the encoder by default?

I also didn't see any test case for this.

**Comment by roccomuso** [comment]
The size is different, hence the checksum.
In my case `5303718` against `5326498` (the input).

The video looks the same

**Comment by themasch** [comment]
I tried the following: generate an output.mkv from a random input.mkv and run the example.js (print out all chunks) on both of them. After that I compared the outputs. It seems to have the same chunks but the start and end of each chunk seem to be different while the size of a chunk seems to stay the same. For me, this indicates a bug. Will have a look into this, thanks for the report!

**Comment by themasch** [comment]
Here a small example of whats happening: 

In the input file the EBML tag starts at 0 and ends at 43 with 4 byte for the Tag-ID and 31 bytes of payload (other tags). 

In the output file the EBEML tag starts at 0 and ends at 36 with 4 byte for the Tag-ID and 31 bytes of payload (other tags). 

Heres the input (first 43 bytes):
```
0000000000000000  1a 45 df a3 01 00 00 00 00 00 00 1f 42 86 81 01  | .E..........B... |
0000000000000010  42 f7 81 01 42 f2 81 04 42 f3 81 08 42 82 84 77  | B...B...B...B..w |
0000000000000020  65 62 6d 42 87 81 02 42 85 81 02                 | ebmB...B...      
```
Heres the output (first 36 bytes): 
```
0000000000000000  1a 45 df a3 9f 42 86 81 01 42 f7 81 01 42 f2 81  | .E...B...B...B.. |
0000000000000010  04 42 f3 81 08 42 82 84 77 65 62 6d 42 87 81 02  | .B...B..webmB... |
0000000000000020  42 85 81 02                                      | B...             |
```
Seems like we are skipping the zeros for some reason. 

This does not happen when we reencode a file that was encoded with node-ebml. 

So throwing output.mkv in the script above and creating output2.mkv creates 2 identical files. 
```
d79cc36796c0c6cc1d891f6ab25575e4  output.mkv
d79cc36796c0c6cc1d891f6ab25575e4  output2.mkv
```

**Comment by themasch** [comment]
Alright, heres the thing: 
EBML users a variable length for encoding integers. 
To parse one of these ints you look at the first byte (from msb to lsb) and find the first 1. If its on the MSB then the length of the int is 1 byte, if its on the second bit the lenght is two bytes etc. You get the value of that int by throwing away the first n bits in the first byte (where n is the number of bytes). 

So when you read a 0x9f  theres the msb is set (0x80) and you get your value by just unsetting that bit (0x9f - 0x80 = 0x1f = 31). 
But this encoding is not unambiguous. You can also store 31 as [0x01 00 00 00 00 00 00 0x1f]. This means your read 8 bytes (since the 1 is on the lsb) and throw away the first 8 bits and just read the value and thats 0x1f = 31. 

So what I see in my test files that many of these lengths seem to be encodede by using way to many bytes. That is the encoder used to create these files randomly (of course not randomly, but by means i don't know about) chooses to encode a value like "163" using 8 bytes instead of two or (in the example above) using 8 bytes for 31 where 1 whould have been fine. 

Could you please check if thats what happens for you, too? Maybe we got another issue that just does not happen for my test file. 

If its just that: I guess we are doing the right thing™ here and someone else is cheaping out on writing vints.

**Comment by themasch** [comment]
Okay, I think these are two seperate issues. #8 is about ints that are bigger than 8 bytes which the Matroska spec explicitly does not allow (` any size from 1 to 8 octets`). The real black magic with big ints seems to happen between 2^53-1 and 2^56-2, so between javascripts max integer size and the maximum integer size thats representable in ebml. 

What I descriped above is about actual small integers (like 31) that are encoded in a way where they use more bytes then nesessary. 

While I totally have to have a look at #8 & #10 again, I don't this issue is related to that.
